### ISSUE TITLE
Saved filename doesn't match returned filename

### ISSUE THREAD

**Issue by rconstantine** [westmonroe/pdf-puppeteer#17]
I'm using 'path' in the puppeteer options to set the name of the file when it is saved to the server. That works fine, but I also return the PDF to the user via res.send(pdf). The name of the file that the browser gets is response.pdf.

Is there a way to see that it gets the same name as I pass into path? Is there another place to set this?

BTW, switching to res.sendFile('full path here') doesn't change the resulting filename but does send the right file.

**Comment by atodd-noms** [comment]
res.header('Content-Type', 'application/pdf')
res.header('Content-Transfer-Encoding', 'binary')
res.header('Content-Disposition', `inline; filename=${filename}`)

**Comment by cr7boulos** [comment]
@atodd-noms  Thanks for the assist. @rconstantine Does this help fix your issue? If so, I will mark this issue as closed.

**Comment by rconstantine** [comment]
I'll give this a try.
