### ISSUE TITLE
# kills page render

### ISSUE THREAD

**Issue by mrfrase3** [westmonroe/pdf-puppeteer#21]
say we have some css in our html
```html
<style>
html {
  color: #aabbcc
}
</style>
```
and that is fed to this 
```js
  await page.goto(`data:text/html,${html}`, {
```
the # is read as a hash in a uri, causing it to only render the html up to that character.

replacing that line with 
```js
  await page.goto(`data:text/html;base64,${Buffer.from(html).toString('base64')}`, {
``` 
fixes the issue. (sending the uri as base64 instead)

**Comment by cr7boulos** [comment]
@mrfrase3 Thanks for submitting this issue and the associated PR. We will review and get back to you shortly.

**Comment by cr7boulos** [comment]
@mrfrase3 

This has been merged in and published in the latest version on npm.
