### ISSUE TITLE
Question : Puppeteer chromium cached in memory ?

### ISSUE THREAD

**Issue by x4080** [westmonroe/pdf-puppeteer#24]
Hi, is Puppeteer chromium cached in memory ? So that in every request it will not re initialized chromium ?

Thanks

**Comment by cr7boulos** [comment]
Hi x4080,

The current implementation of pdf-pupetteer does not cache puppeteer in memory. It creates a new instance per request.

**Comment by x4080** [comment]
@cr7boulos Thanks
