### ISSUE TITLE
TypeScript definitions? (*.d.ts)

### ISSUE THREAD

**Issue by yurist38** [westmonroe/pdf-puppeteer#26]
Hello! Do you consider adding TypeScript definitions? Or maybe even migrating to TS?

**Comment by cr7boulos** [comment]
@yurist38 

Yes, I think TypeScript definitions would be a valuable add at this time. I'll mark this as an enhancement. The next step from here would be creating a PR against this repo:  https://github.com/types to add pdf-puppeteer type definitions to it and then updating the docs to let users know they can install type definitions for pdf-puppeteer.

**Comment by yurist38** [comment]
We could also commit the definitions file in this repo. So users don't have to install a separate package with types. What do you think? Do you still prefer to keep definitions separately? I have already added types into my project, so I can open the PR. Just let me know please what is better for you.

**Comment by cr7boulos** [comment]
Sure, feel free to put up the PR against this repo. Thanks!
