### ISSUE TITLE
UTF-8 Problem

### ISSUE THREAD

**Issue by NazimMertBilgi** [westmonroe/pdf-puppeteer#31]
```
convertHTMLToPDF(
        "<h2>ÖMÜR KAYIP</h2>",
        pdf => {
            console.log(pdf)
        },
        {path:"try.pdf"},
        {args: ['--no-sandbox']},
        true
    ).catch(err => {
        console.log(err);
    });
```

Result = **Ã–MÃœR KAYIP**

please help me.

**Comment by cr7boulos** [comment]
@NazimMertBilgi 
It seems like the version of puppeteer we are using is broke the rendering of UTF-8 characters. I will look to modify the version of puppeteer we reference to try and fix this issue.

**Comment by NazimMertBilgi** [comment]
Will puppeteer version 1.17 solve the problem? @cr7boulos

**Comment by NazimMertBilgi** [comment]
I solved the problem, it was enough to add them to the top of my page.

`<head>
    <meta charset="UTF-8">
</head>`
