### ISSUE TITLE
puppeteer launch options

### ISSUE THREAD

**Issue by PiXy79** [westmonroe/pdf-puppeteer#5]
Currently it is not possible to modify the default puppeteer [launch options](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions). 

It would be very useful to customize puppeter options and, for instance add the options to run even in a dockerized environment.

**Comment by joehiggs** [comment]
I can take a look at this over the weekend most likely, but feel free to submit a PR for it!

**Comment by joehiggs** [comment]
@PiXy79 Closing this issue as the functionality has been added per #10
